spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/course_arrange_v3

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#项目配置
project:
  projectName: 课程自动排课系统
  shiro:
    #免认证端口
    anonUrl: /,/login,/login/**,/logout,/nin-career,/druid
  #管理员信息(id,名称,账号,密码)
  admin:
    id: 100000000000000000
    name: admin
    code: admin
    password: 123456





